### ISSUE TITLE
Fix error on CRAN

### ISSUE THREAD

**Issue by sinhrks** [sinhrks/ggfortify#107]
https://cran.r-project.org/web/checks/check_results_ggfortify.html

**Comment by terrytangyuan** [comment]
Hmm weird. Do you know any possible reason why lfda is not found? Is this the new submission?

**Comment by sinhrks** [comment]
Not sure... I've fixed error cases on travis, and going to dubmit to CRAN.

Do you have anything should be included?

**Comment by terrytangyuan** [comment]
I see. Nope.

**Comment by sinhrks** [comment]
OK, thanks:)
