### ISSUE TITLE
Package got removed from the CRAN

### ISSUE THREAD

**Issue by sciatro** [sinhrks/ggfortify#113]
https://cran.r-project.org/web/packages/ggfortify/index.html shows:

```
Package ‘ggfortify’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2016-05-02 as check problems were not corrected despite reminders.
```

`> install.packages` fails as expected; however, the `devtools` install continues to work as expected after:

```
library(devtools)
install_github('sinhrks/ggfortify')
```

**Comment by terrytangyuan** [comment]
@sinhrks Did you get a chance to submit the fix yet?

**Comment by kaji331** [comment]
Could you add Rtsne package support? It is famous in single cell biology field.

**Comment by sinhrks** [comment]
Thanks for the report. I'm fixing some points reported from CRAN, and will re-submit sooner.

@kaji331 As I don't familiar with ``Rtsne``, PR is appreciated:)

**Comment by sinhrks** [comment]
Closed with #112.

**Comment by sjmgarnier** [comment]
@sinhrks It looks like ggfortify was again removed from CRAN.

**Comment by terrytangyuan** [comment]
@sinhrks Could you take a look as soon as you can as many packages also depend on ggfortify? Thanks.

**Comment by terrytangyuan** [comment]
```
Package ‘ggfortify’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2018-01-27 as check problems were not corrected despite reminders.
```

**Comment by sjmgarnier** [comment]
@terrytangyuan @sinhrks Any update on this?

**Comment by terrytangyuan** [comment]
I resubmitted the package with a couple of temporary fixes. It should be on CRAN soon. Thank you for your support and patience!

**Comment by sjmgarnier** [comment]
@terrytangyuan Thanks!
