### ISSUE TITLE
How to add different point type for kmeans plot?

### ISSUE THREAD

**Issue by kaji331** [sinhrks/ggfortify#115]
for example:

d <- rnorm(100)
i <- c(rep("A",50),rep("B",50))
fit <- kmeans(d,2,nstart=1000)
mds <- cmdscale(dist(d))
ggplot(as.data.frame(mds)) + geom_point(aes(mds[,1],mds[,2],shape=i),size=3)

So, I don't know how to use "i" by autoplot for different point...shape in autoplot is a logical value.

**Comment by sinhrks** [comment]
You can use `shape` kwds. See `help(ggbiplot)` for other kwds.

```
km <- kmeans(iris[-5], 3)
autoplot(km, data = iris, shape = 3)
```

![rplot](https://cloud.githubusercontent.com/assets/1696302/15892611/98b5f500-2db5-11e6-8f50-dbcd1f6dfdd3.png)
