### ISSUE TITLE
Change Legend Title

### ISSUE THREAD

**Issue by fkgruber** [sinhrks/ggfortify#121]
Hi
How can I change the title of the legend? Right now it is always called strata

I tried scale_color_discrete(name = xlab) but then I got 2 legend:

![image](https://cloud.githubusercontent.com/assets/4311763/17335306/7ecaf4d4-58a7-11e6-915c-857a03df339b.png)

**Comment by fkgruber** [comment]
I just figured it out
autoplot(survc, type = "fill", alpha = 0.1, pVal = T,
                           title = ylab, legTitle = xlab, ylab = ylab,
                           legLabs = levels(toplotsim$x))  +
                scale_color_discrete(name = xlab) +
                scale_fill_discrete(name = xlab)

![image](https://cloud.githubusercontent.com/assets/4311763/17335503/2e989542-58a8-11e6-8434-ddc63f9ff77a.png)

**Comment by fkgruber** [comment]
Perhaps it would be nice to have an argument allowing you to decide the legend title?

**Comment by terrytangyuan** [comment]
@fkgruber Yeah that would be good too. Feel free to submit a PR! `autoplot` returns a ggplot2 object so you can easily extend with additional ggplot2 syntax.
