### ISSUE TITLE
Add PC1/2 scores to graph axes

### ISSUE THREAD

**Issue by lrocax** [sinhrks/ggfortify#122]
Hi,

Is it possible to add the PC1 and PC2 scores to the axes labels (like in ggbioplot: https://github.com/vqv/ggbiplot)?

Thanks

**Comment by terrytangyuan** [comment]
Autoplot would return a ggplot object so you can override the axes labels by adding additional ggplot2 syntax.

**Comment by terrytangyuan** [comment]
I mentioned this functionality in our paper: https://journal.r-project.org/archive/accepted/tang-horikoshi-li.pdf

Please see the section for PCA. You can apply additional ggplot2 code to further enhance the plot.

**Comment by sinhrks** [comment]
Thx for the report. You can pass arbitrary char vectors to ``loadings.label.label`` (you'll see a warning but it should work):

```
autoplot(prcomp(iris[-5]), loadings.label = TRUE, loadings.label.label = c('arrow1','arrow2', 'arrow3', 'arrow4')
```

![rplot](https://cloud.githubusercontent.com/assets/1696302/18824809/b874b070-83ff-11e6-9f3f-abc5678d783c.png)
