### ISSUE TITLE
Latest build failed in dev env

### ISSUE THREAD

**Issue by terrytangyuan** [sinhrks/ggfortify#124]
Details [here](https://travis-ci.org/sinhrks/ggfortify/jobs/162475772). 

@sinhrks Could you look into this when you get a chance?

**Comment by sinhrks** [comment]
sure, will do.

**Comment by sinhrks** [comment]
Looks to be caused by deps installation, needs to look in further.

**Comment by terrytangyuan** [comment]
Seems to be fixed by itself. ;-)
