### ISSUE TITLE
fortify for `raster::raster` objects

### ISSUE THREAD

**Issue by Rekyt** [sinhrks/ggfortify#125]
Hey,
Thanks for building this awesome package that helps working with `ggplot2` in all circumstances ;)

There are quite a number of methods for `sp` objects in `ggfortify` but none for `raster` objects.
The `rasterVis` package include a `fortify()`-like function in its function [`gplot()`](https://github.com/oscarperpinan/rastervis/blob/master/R/gplot.R#L17-L24) .
I was thinking of implementing something similar in `ggfortify`.

**Comment by terrytangyuan** [comment]
Pull request is welcomed!
