### ISSUE TITLE
Autoplot for spline basis

### ISSUE THREAD

**Issue by DarwinAwardWinner** [sinhrks/ggfortify#128]
A while back, I wrote an autoplot method for spline basis objects: http://stats.stackexchange.com/a/179099/5736

Would you be interested in including this in ggfortify?

**Comment by terrytangyuan** [comment]
Welcome pull request!

**Comment by sinhrks** [comment]
Looks nice!

**Comment by terrytangyuan** [comment]
Feel free to add some vignettes! @DarwinAwardWinner Looking good!
