### ISSUE TITLE
survfit error on plot

### ISSUE THREAD

**Issue by fabioand2k** [sinhrks/ggfortify#130]
Hi,

please, when i try to run

library(ggfortify)
library(survival)
fit <- survfit(Surv(time, status) ~ sex, data = lung)
autoplot(fit)

gave this error:
Error: GeomConfint was built with an incompatible version of ggproto.
Please reinstall the package that provides this extension.

thank you so much

**Comment by terrytangyuan** [comment]
The error seems obvious. You need to reinstall those packages for compatibility issue.

**Comment by fabioand2k** [comment]
Hi,
im sorry do you means reinstall ggfortify, survival or ggplot2 ?

thank you for your support.

**Comment by terrytangyuan** [comment]
GeomConfInt and ggproto.

**Comment by fabioand2k** [comment]
thank you so much!!!

**Comment by terrytangyuan** [comment]
No problem.

**Comment by fabioand2k** [comment]
Terry,
sorry again, i am beginner in R.
GeomConfInt and ggproto are not packages in CRAN.
i try to remove ggfortify and reinstall and same error.

**Comment by terrytangyuan** [comment]
Oops sorry they are not packages but objects. Try reinstall survival?

**Comment by fabioand2k** [comment]
i will try now. just a second

**Comment by fabioand2k** [comment]
hi Terry,,

same error after remove and reinstall survival.

thanks

**Comment by terrytangyuan** [comment]
Try reinstall ggplot

**Comment by fabioand2k** [comment]
from github or cran, cause i did from cran and same error.

this is was my first try.

**Comment by fabioand2k** [comment]
you can run this code in your environment ?

**Comment by terrytangyuan** [comment]
I'll give it a try later. Not near my computer.

**Comment by fabioand2k** [comment]
thank you my friend

**Comment by yutannihilation** [comment]
Hi, I've reproduced the error with the same code on my Windows environment (R 3.3.2) and found that `install.packages("ggfortify", type = "source")` solves the problem, though I don't know why...

```r
install.packages("ggfortify")

library(ggfortify)
library(survival)
fit <- survfit(Surv(time, status) ~ sex, data = lung)
autoplot(fit)
#> Error: GeomConfint was built with an incompatible version of ggproto.
#> Please reinstall the package that provides this extension.

# (restart R session)

install.packages("ggfortify", type = "source")

library(ggfortify)
library(survival)
fit <- survfit(Surv(time, status) ~ sex, data = lung)
autoplot(fit)
# (No error)
```

**Comment by terrytangyuan** [comment]
Perhaps the fix wasn't on CRAN yet. Can you try install Github version?

**Comment by terrytangyuan** [comment]
I was able to get the same results as well. `devtools::install_github("sinhrks/ggfortify")` works as well. 

I think the problem is the version on CRAN was built using old version of other packages (not install from source) https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/ggfortify_0.2.0.tgz

So solution is: install from Github or install from source. @fabioand2k 

Thanks for reporting @fabioand2k and your help @yutannihilation!

**Comment by sinhrks** [comment]
Yeah, will release on CRAN hopefully after #126.  Also there is a erroneous case seems to be caused by ggplot2 side. I'll revisit and forward it to ggplot2.

- https://github.com/sinhrks/ggfortify/blob/dcb291a3fcccff79a30213ccea99cddcc1ad67e0/tests/testthat/test-surv.R#L190
