### ISSUE TITLE
NEWS File Not Visible on CRAN

### ISSUE THREAD

**Issue by DarioS** [sinhrks/ggfortify#134]
Many packages have a NEWS or README file with links on their CRAN webpage. `ggfortify` uses an unusual file format for these, so these files are not visible to the end user. Also, the NEWS file is missing information about what's new in the 0.3 version.

**Comment by terrytangyuan** [comment]
Thanks for reporting! I just pushed the fix. @sinhrks Do you think we should push this minor change?

**Comment by sinhrks** [comment]
Thx for the report and fix.

As CRAN isn't willing to accept frequent pkg update, going to wait until next release.
