### ISSUE TITLE
autoplot fails on poly regression

### ISSUE THREAD

**Issue by DasHammett** [sinhrks/ggfortify#140]
Hi, 

I get similar error message as in #137 when doing any polynomial regression.
Please see reproducible example:

```
library(ggfortify)
model <- lm(mpg ~ poly(hp, 2, raw = TRUE),data = mtcars)
autoplot(model)
Error: Each variable must be a 1d atomic vector or list.
Problem variables: 'poly(hp, 2, raw = TRUE)'

par(mfrow = c(2,2))
plot(model)
```

**Comment by terrytangyuan** [comment]
I am travelling and not able to help with this for a while. Are you using the most recent version on Github? cc: @sinhrks

**Comment by DasHammett** [comment]
Hi!

No worries, you will have a look upon your return. 
In the meantime I can still run the regression with `formula = y ~ x + I(x²)` as writing the regression like this works as expected.

The first thing I did is to use the github version, but unfortunately I experienced the same error.

Thank you for having a look when you can.

**Comment by sinhrks** [comment]
@DasHammett thx for the report. the issue is caused by matrix contained in the explanatory values ( almost the same as #137). pls use the latest master.
