### ISSUE TITLE
Variable Name in Survival Plot Legends

### ISSUE THREAD

**Issue by DarioS** [sinhrks/ggfortify#143]
By default, `autoplot` uses the names from `survivalFit[["strata"]]` as the legend levels. They have a `variableName=value` format. Programmer's variable names are not something that a figure to be published in a medical journal should have displayed. Perhaps `autoplot` should use code like `gsub(".*=", '', strataNames)` to place only the level name in the legend. `autoplot` also lacks any legend customisation options, such as the legend title.

**Comment by terrytangyuan** [comment]
Theoretically you can always append new ggplot syntax to autopilot result (which is ggplot object), using plus sign. Have you tried this?

**Comment by DarioS** [comment]
Yes, that works for me, but the default output could be better and require less end-user interaction is what I am suggesting. Both renaming and reordering the labels after the plot is generated is asking for trouble, such as the colours being associated with incorrect text labels, if not done carefully.

**Comment by terrytangyuan** [comment]
You are always welcome to submit a PR to fix them! It would be great if you
can provide a reproducible example.

**Comment by DarioS** [comment]
A minimal example is:

    library(ggfortify)
    library(survival)
    
    livingStatus <- sample(0:1, 20, replace = TRUE)
    followupTime <- rpois(20, 300)
    samplesGroups <- factor(sample(c("Low", "High"), 20, replace = TRUE), levels = c("Low", "High"))
    
    survivalData <- Surv(followupTime, livingStatus)
    survivalFit <- survfit(survivalData ~ samplesGroups)
    autoplot(survivalFit, conf.int = FALSE, ylim = c(0, 1))

The legend labels display the programmer's variable name prefixed to every level and, unlike ordinary `ggplot2` plots, ignore factor level ordering, instead displaying the levels alphabetically, as described in #142. This would be like `ggplot2` having labels of the form `cylinders=4, cylinders=6, cylinders=8` by default for its legends, which is ugly and creates lots of whitespace under the legend by shrinking the width of the main plot.

Software maintenance is hard, but worthwhile. I'm fully occupied maintaining my own software, so I wouldn't have time help with this task any time soon.
