### ISSUE TITLE
importing autoplot

### ISSUE THREAD

**Issue by kendomaniac** [sinhrks/ggfortify#149]
Dear Sir,
I have written a function in which I used ggfortify to plot PCA the overall function is pretty simple, see below.
When I do the package (https://github.com/kendomaniac/docker4seq) check I get the following warning:
samplesPca: no visible global function definition for ‘autoplot’
Undefined global functions or variables:
  autoplot 

I import in my function ggfortify, but it seems that the autoplot in not imported from ggfortify
Could please suggest a way of fix this problem? 
Cheers
Raf

######################################
#' @title Sample PCA on raw counts
#' @description This function runs PCA via ggfortify and ggplot2 on the output of samples2experiments function
#'
#' @param data, the counts dataframe generated by samples2experiemtn function
#' @param groups, a character string indicating association between samples and experimental groups
#' @param label, a boolean value, TRUE or FALSE to ad the names of the samples in the plot
#' @param label.size, an integer value indicating the size of label
#' @param output.file, a tab delimited file in which the first column are names from counts object from experiment.table.Rda file generated with samples2experiment function. In the pdf will be also rpesent the istigram fo the PCA variance dispersion.
#' @import  ggfortify
#' @importFrom graphics plot
#' @importFrom grDevices pdf
#' @importFrom grDevices dev.off
#' @importFrom stats prcomp
#' @return a pdf file with the PCA plot
#' @examples
#'\dontrun{
#'    load("test_experiment.tables.Rda")
#'    samplesPca(data=counts, groups=c("d","eb","wb","ws"), label = TRUE, label.size = 3)
#'    output.file="test.pdf", label = FALSE, label.size = 3)
#' }
#' @export
samplesPca <- function(data, groups=NULL, output.file=NULL, label, label.size){
    if(!is.null(groups)){
        data.df <- data.frame(names(data), as.factor(groups))
        names(data.df) <- c("samples","groups")
        if(is.null(output.file)){
          autoplot.prcomp(prcomp(t(data)), data=data.df, colour='groups', label = label, label.size = label.size)
        }else{
          pdf(output.file)
             plot(prcomp(t(data)), main="")
             autoplot(prcomp(t(data)), data=data.df, colour='groups', label = label, label.size = label.size)
          dev.off()
          cat(paste("\nPCA is saved in ",output.file, sep=""))
        }
    }else{
      if(is.null(output.file)){
        autoplot(prcomp(t(data)))
      }else{
        pdf(output.file)
          plot(prcomp(t(data)), main="")
          autoplot(prcomp(t(data)))
        dev.off()
        cat(paste("\nPCA is saved in ",output.file, sep=""))
      }
    }
    return(data.df)
}

**Comment by terrytangyuan** [comment]
Try ggfortify::autoplot(prcomp(t(data)))?

**Comment by kendomaniac** [comment]
Hi Terry,
thanks for the quick answer.
I fixed the inconsistencies.
I used you suggestion:
but now I get during the package check:
Missing or unexported object: ‘ggfortify::autoplot’
and if I try to run the function I get:
> library(docker4seq)
> samplesPca(data=counts, groups=c("d","eb","wb","ws"), label = TRUE, label.size = 3)
Error: 'autoplot' is not an exported object from 'namespace:ggfortify'


###############################################################
#' @title Sample PCA on raw counts
#' @description This function runs PCA via ggfortify and ggplot2 on the output of samples2experiments function
#'
#' @param data, the counts dataframe generated by samples2experiemtn function
#' @param groups, a character string indicating association between samples and experimental groups
#' @param label, a boolean value, TRUE or FALSE to ad the names of the samples in the plot
#' @param label.size, an integer value indicating the size of label
#' @param output.file, a tab delimited file in which the first column are names from counts object from experiment.table.Rda file generated with samples2experiment function. In the pdf will be also rpesent the istigram fo the PCA variance dispersion.
#' @import  ggfortify
#' @importFrom graphics plot
#' @importFrom grDevices pdf
#' @importFrom grDevices dev.off
#' @importFrom stats prcomp
#' @return a pdf file with the PCA plot
#' @examples
#'\dontrun{
#'    load("test_experiment.tables.Rda")
#'    samplesPca(data=counts, groups=c("d","eb","wb","ws"), label = TRUE, label.size = 3)
#'    output.file="test.pdf", label = FALSE, label.size = 3)
#' }
#' @export
samplesPca <- function(data, groups=NULL, output.file=NULL, label, label.size){
    if(!is.null(groups)){
        data.df <- data.frame(names(data), as.factor(groups))
        names(data.df) <- c("samples","groups")
        if(is.null(output.file)){
          ggfortify::autoplot(prcomp(t(data)), data=data.df, colour='groups', label = label, label.size = label.size)
        }else{
          pdf(output.file)
             plot(prcomp(t(data)), main="")
             ggfortify::autoplot(prcomp(t(data)), data=data.df, colour='groups', label = label, label.size = label.size)
          dev.off()
          cat(paste("\nPCA is saved in ",output.file, sep=""))
        }
    }else{
      if(is.null(output.file)){
        ggfortify::autoplot(prcomp(t(data)))
      }else{
        pdf(output.file)
          plot(prcomp(t(data)), main="")
          ggfortify::autoplot(prcomp(t(data)))
        dev.off()
        cat(paste("\nPCA is saved in ",output.file, sep=""))
      }
    }
    return(data.df)
}

**Comment by terrytangyuan** [comment]
Try put ggfortify package in your imports in DESCRIPTION instead of DEPENDS. Add `#' @import rARPACK` to your function roxygen comments. And then use `ggfortify::autoplot` in your code above.

**Comment by terrytangyuan** [comment]
Sorry I meant `#' @import ggfortify` instead of `rARPACK`

**Comment by kendomaniac** [comment]
HI Terry,
I did as you suggested:
now in the DESCRIPTION I have:
Depends:
    R (>= 3.2.0), refGenome
Imports: ggfortify

the #' @import ggfortify was already in the roxigen comments.

Unfortunately I still get during the package check I get:

checking dependencies in R code ... NOTE
Missing or unexported object: ‘ggfortify::autoplot’

trying to run the function I get
> library(docker4seq)
Loading required package: refGenome
Loading required package: doBy
Loading required package: RSQLite

 samplesPca(data=counts, groups=c("d","eb","wb","ws"), label = TRUE, label.size = 3)
Error: 'autoplot' is not an exported object from 'namespace:ggfortify'

**Comment by terrytangyuan** [comment]
When you run this code by itself, does it work? Does it find autoplot?

**Comment by terrytangyuan** [comment]
I see. `autoplot` is indeed not exported. Could you try `ggfortify:::autoplot.prcomp()`? (Note the three dots)

**Comment by kendomaniac** [comment]
Yes but only if I use autoplot
> counts <- read.table("test_counts.txt", sep="\t", header=T, row.names=1)
> data=counts
> groups=c("d","eb","wb","ws")
> label = TRUE
> label.size = 3
> data.df <- data.frame(names(data), as.factor(groups))
> names(data.df) <- c("samples","groups")
> autoplot(prcomp(t(data)), data=data.df, colour='groups', label = label, label.size = label.size)
with 
> ggfortify::autoplot(prcomp(t(data)), data=data.df, colour='groups', label = label, label.size = label.size)
Error: 'autoplot' is not an exported object from 'namespace:ggfortify'

[Rplot.pdf](https://github.com/sinhrks/ggfortify/files/753189/Rplot.pdf)

[test_counts.txt.zip](https://github.com/sinhrks/ggfortify/files/753190/test_counts.txt.zip)

**Comment by terrytangyuan** [comment]
See my last comment.

**Comment by kendomaniac** [comment]
In the function:
ggfortify:::autoplot.prcomp(prcomp(t(data)), data=data.df, colour='groups', label = label, label.size = label.size)
during package check:
checking dependencies in R code ... NOTE
Unexported object imported by a ':::' call: ‘ggfortify:::autoplot.prcomp’
  See the note in ?`:::` about the use of this operator.

However, although there is the NOTE this time testing the function I do not get any error and I get the plot :)
Thanks!
Raf

**Comment by terrytangyuan** [comment]
Great! You can perhaps put it back to in `Depends`. Glad helped.

**Comment by kendomaniac** [comment]
OK thanks
