### ISSUE TITLE
Unnecessary post_fortify in survfit Fortify

### ISSUE THREAD

**Issue by DarioS** [sinhrks/ggfortify#151]
The final line of `fortify.survfit`, `post_fortify(d)`, seems to be a no-op.

    > d2 = post_fortify(d)
    > identical(d, d2)
        [1] TRUE

Should it just be removed? This might be the same as #102.

**Comment by sinhrks** [comment]
Thx for the comment. Even though some func doesn't rely on ``post_fortify`` ATM, it is kept in case of adding common op in future.
