### ISSUE TITLE
Cannot change values drawn on the X axis in autoplot.glmnet()

### ISSUE THREAD

**Issue by vadimus202** [sinhrks/ggfortify#156]
The `xvar` argument to `autoplot.glmnet()`has no effect on the plots. The plots always default to "norm" (L1-norm) values.
```
library(ggfortify)

autoplot(glmnet::glmnet(data.matrix(Orange[-3]), data.matrix(Orange[3])), xvar="lambda")
autoplot(glmnet::glmnet(data.matrix(Orange[-3]), data.matrix(Orange[3])), xvar="dev")
```
![image](https://cloud.githubusercontent.com/assets/7230548/23219320/c2c36dd4-f8ec-11e6-9c4b-ba33b1b57854.png)

![image](https://cloud.githubusercontent.com/assets/7230548/23219355/d327724c-f8ec-11e6-9ea0-3f53825ba54e.png)

**Comment by terrytangyuan** [comment]
Thanks! Fixed.
