### ISSUE TITLE
Incorrect Y axis label in autoplot.cv.glmnet()

### ISSUE THREAD

**Issue by vadimus202** [sinhrks/ggfortify#157]
The Y axis label in `autoplot.cv.glmnet()` plot reflect the default argument in `glmnet::cv.glmnet(type.measure="mse")`, even when the `type.measure="auc"` ( I haven't tested other available options). Please compare the results from `glmnet::plot.cv.glmnet()`

I can fix the axis label manually, but I thought I'd bring it to your attention. 
Thanks

```
library(glmnet)
library(ggfortify)
fit <- cv.glmnet(data.matrix(mtcars[-8]), data.matrix(mtcars[8]), family ="binomial", type.measure="auc", nfolds = 3)
autoplot(fit)
plot(fit)
```

![image](https://cloud.githubusercontent.com/assets/7230548/23226833/0a5fcb34-f905-11e6-9aa7-0850e8bd6c3f.png)
![image](https://cloud.githubusercontent.com/assets/7230548/23226841/109ad6ec-f905-11e6-8591-e9ea5d845717.png)

**Comment by sinhrks** [comment]
@vadimus202 Thx, will fix it.

**Comment by terrytangyuan** [comment]
@vadimus202 This is now fixed. Thanks for reporting!
