### ISSUE TITLE
autoplot PCA Specify Components

### ISSUE THREAD

**Issue by DarioS** [sinhrks/ggfortify#164]
Either the documentation doesn't explain it, or it's not possible, but I'd like to plot PC2 vs. PC3 and I can't. I checked the Examples section of `?autoplot.prcomp` and the Plotting PCA vignette.

**Comment by terrytangyuan** [comment]
It's actually available since this PR: https://github.com/sinhrks/ggfortify/pull/146

We indeed need to add more examples though. Right now you can find some tests that could serve as examples.

**Comment by lselzer** [comment]
I believe you can close this now
