### ISSUE TITLE
 autoplot绘制时间序列预测图时，部分参数无效

### ISSUE THREAD

**Issue by Archergy** [sinhrks/ggfortify#165]
我是在微信上看到你的那段介绍的，所以把代码运行了一遍，期间出现了点小问题
代码如下：
```
library(ggfortify)
library(forecast)
d.arima <- auto.arima(AirPassengers)
d.forecast <- forecast(d.arima, level = c(95), h = 50)
autoplot(d.forecast, ts.colour = 'firebrick1', predict.colour = 'red', #Error
         predict.linetype = 'dashed', conf.int = F)
```
最后一行命令中的`ts.colour, predict.colour, pridict.linetype, conf.int`这些参数对结果无影响，其绘出的图与`autoplot(d.forecast)`完全相同。
在R3.3.3和3.4.0环境中测试的。

Ps.Please forgive me for using Chinese, because my English isn't very well.

**Comment by terrytangyuan** [comment]
我试了一下这些参数都没有问题，可以改变颜色和线的形状，你是在RStudio里面跑的还是？

**Comment by Archergy** [comment]
是在win10最新版的Rstudio里面跑的，我在Console中试了一下还是那样，很奇怪

**Comment by terrytangyuan** [comment]
不好意思我手头没有win10可以跑，估计是你的环境有问题导致出来的图片没有更新，你试试把他们写到文件里面去？
