### ISSUE TITLE
Possible error in pca_common when plotting PCs other than 1 & 2?

### ISSUE THREAD

**Issue by sciatro** [sinhrks/ggfortify#169]
Is it possible that ``lam <- object$sdev[1L:2L]`` in [autoplot.pca_common](https://github.com/sinhrks/ggfortify/blob/master/R/fortify_stats.R#L258)  should be ``lam <- object$sdev[, c(x, y)]`` after https://github.com/sinhrks/ggfortify/pull/146?

I'm not sure just got some funky results that I was trying to track down.

Thanks for all the great work on the this package.

**Comment by terrytangyuan** [comment]
@lselzer Could you take a look? @sciatro Thanks for reporting! It would be better if you could post a minimal reproducible example here.

**Comment by lselzer** [comment]
@sciatro You are right, the eigenvectors are scaled by the inverse matrix of the root of the eigenvalues (i.e. their standard deviations). I have fixed it but I have to fix the tests. I will issue a PR when I do that.
