### ISSUE TITLE
Y axis tick labels in ggdistribution

### ISSUE THREAD

**Issue by sctyner** [sinhrks/ggfortify#174]
The Y axis tick labels are not technically accurate. The y axis in the plot of a probability distribution function is not the probability or percent as the y axis in a `ggdistribution` plot shows. Probability is calculated from area under the curve, not from the value of the density function. The labelling of the axes as percents is inaccurate and confusing, especially in an example like the one below: 
```
ggdistribution(dnorm, seq(1.5198, 1.5202, .000005), mean = 1.52, sd = .00005) 
``` 
![rplot](https://user-images.githubusercontent.com/6137322/28180604-32d3dd82-67cb-11e7-8088-90014d91b928.jpeg)
I appreciate what you were going for by changing the labels to be a bit neater, but they are simply not correct.

**Comment by terrytangyuan** [comment]
Thanks for the report! This definitely seems like a bug. I haven't got a chance to look into this yet but pull request is always welcomed! The related code is [here](https://github.com/sinhrks/ggfortify/blob/55b60cea8c4f31889ab5777bc68b6b5d162a0713/R/fortify_stats_density.R).

**Comment by terrytangyuan** [comment]
@sctyner I pushed a fix to remove the incorrectly usage of `scales::percent`. It should now display the raw values of the distribution. In this case you should expect to see the peak of that distribution is around 8000. Thanks for the report!
