### ISSUE TITLE
Relation with tidyverse/broom

### ISSUE THREAD

**Issue by yoursdearboy** [sinhrks/ggfortify#179]
Greetings everyone.

What do you think about [tidyverse/broom](https://github.com/tidyverse/broom)? It seems that this package solves a major part of ggfortify needs - converting objects to tidy data and there's no such thing as `autoplot`, so it is not a replacement.

**Comment by terrytangyuan** [comment]
See related issue: https://github.com/sinhrks/ggfortify/issues/17

Contributions are welcomed!
