### ISSUE TITLE
Display PCA biplot loading labels without arrows

### ISSUE THREAD

**Issue by mindstorm555** [sinhrks/ggfortify#182]
Hi Guys,

Would it be possible to make loading arrows and loading labels independant for ggbiplot? At the moment loadings = F, loadings.label = T generates both arrows and labels which is identical to having loadings = T.
From my own playing around with trace( ), removing lines 48 - 50 from ggbiplot removes the arrows so would it be possible to accommodate this within the function?

**Comment by terrytangyuan** [comment]
Could you give a more specific example and link me to those code (which file does line 48-50 belong to)? Pull request is always welcomed too if you want to submit the change and paste an example output here.

**Comment by terrytangyuan** [comment]
I took a look at this again. I don't think it's valuable since there is no point displaying only the labels without the arrows. You wouldn't know what those labels are. Closing this for now but feel free to give me a more specific use case you have. Thanks for reporting!
