### ISSUE TITLE
Your package was removed from CRAN!!!!!

### ISSUE THREAD

**Issue by oldregan** [sinhrks/ggfortify#185]
Hi, guys,
    I love your package. But I just found that your ggfortify was removed from CRAN two days ago. Can you update your package on CRAN as soon as possible? I would really appreciate it!!!!

Min

**Comment by terrytangyuan** [comment]
Thanks for your support! We’ll try get it back to CRAN as soon as possible but in the meantime you can install from Github directly following [instructions here](https://github.com/sinhrks/ggfortify#installation).

**Comment by terrytangyuan** [comment]
I resubmitted the package with a couple of temporary fixes. It should be on CRAN soon. Thank you for your support and patience!

**Comment by oldregan** [comment]
Thanks,Terry!
