### ISSUE TITLE
PCA plot coordinates

### ISSUE THREAD

**Issue by connorrogerson** [sinhrks/ggfortify#186]
It's unclear how autoplot transforms the PC values to the coordinates that it plots. 
Would be useful to be able to extract the values to replot the PCA.

**Comment by terrytangyuan** [comment]
You can use `ggfortify::fortify()` to get the data used for plotting.

**Comment by connorrogerson** [comment]
Thanks for this. I've had a go and this just outputs exactly the same as pca$x i.e. the PC scores. What I want is the actual coordinates that autoplot plots.


________________________________

**Comment by terrytangyuan** [comment]
I see. You can try this:
https://stackoverflow.com/questions/12218440/is-it-possible-to-get-the-transformed-plot-data-e-g-coordinates-of-points-in

**Comment by connorrogerson** [comment]
Perfect!!!

**Comment by terrytangyuan** [comment]
Great! Is it working for you? Feel free to close the issue if so.
