### ISSUE TITLE
Remove label legend

### ISSUE THREAD

**Issue by obenno** [sinhrks/ggfortify#191]
Hi, 

Thanks for the amazing package. Is there a way to remove label legend which is a small "a" in ggforty? Some parameters to work as geom_text(show.legend=F)? Thanks.

Bests,
oben

**Comment by terrytangyuan** [comment]
Thanks for the issue. Could you give a minimal example?

**Comment by obenno** [comment]
Thanks for reply.

For pca plots, 
I would like to achieve a plot like
`pca.value <- as.data.frame(prcomp(iris[-5])$x)
ggplot(cbind(pca.value, iris[5]), aes(PC1, PC2, color=Species))+geom_point()+geom_text(aes(label=rownames(iris)), show.legend=F)`
legend without tiny a of geom_text. Thanks.

**Comment by obenno** [comment]
Thanks for reply.

For pca plots,
I would like to achieve a plot like
```
pca.value <- as.data.frame(prcomp(iris[-5])$x)
ggplot(cbind(pca.value, iris[5]), aes(PC1, PC2, color=Species))+geom_point()+geom_text(aes(label=rownames(iris)), show.legend=F)
```
legend without tiny a of geom_text. Thanks.

**Comment by terrytangyuan** [comment]
I am not sure what you meant. The following code could produce similar plots:
```
library(ggfortify)
autoplot(prcomp(iris[-5]), data = iris, colour = 'Species', label = TRUE)
```
Is this what you need?

**Comment by obenno** [comment]
Nope, I mean a different legend.

![with "a"](/home/xzx/Pictures/Selection_087.png)
![without "a"](/home/xzx/Pictures/Selection_088.png)

**Comment by obenno** [comment]
![with a] (/home/xzx/Pictures/Selection_087.png)

![without a] (/home/xzx/Pictures/Selection_088.png)

**Comment by obenno** [comment]
![with a](/home/xzx/Pictures/Selection_087.png)
![without a](/home/xzx/Pictures/Selection_087.png)

**Comment by obenno** [comment]
Sorry for the confusing codes, which I mean is 

![With "a"](https://user-images.githubusercontent.com/6121668/37810723-c01df9f2-2e90-11e8-872d-f80c52162996.png)
![Without "a"](https://user-images.githubusercontent.com/6121668/37810729-ca789966-2e90-11e8-815f-b3684fa3ae2b.png)

**Comment by terrytangyuan** [comment]
Thanks. But I never saw those a's for some reason. Perhaps something's wrong with your ggplot2 version？

**Comment by terrytangyuan** [comment]
Thanks! Seems like the following two plots indeed seem problematic and I could reproduce the problem:
```
df <- iris[c(1, 2, 3, 4)]
autoplot(prcomp(df), data = iris, colour = 'Species', shape = FALSE, label.size = 3)
autoplot(prcomp(df), data = iris, colour = 'Species', label = TRUE, label.size = 3)
```

**Comment by obenno** [comment]
Thanks~

**Comment by terrytangyuan** [comment]
I just pushed an update (install via `devtools::install_github('sinhrks/ggfortify')`). You can now provide `label.show.legend`, e.g. 
```
autoplot(prcomp(df), data = iris, colour = 'Species', label = TRUE, label.size = 3, label.show.legend = FALSE)
```
This should fix the "a" issue. Let me know if it fixes things for you. Thanks!

**Comment by obenno** [comment]
Thanks a lot, it perfectly works!

**Comment by Jahadsoorni** [comment]
> I just pushed an update (install via `devtools::install_github('sinhrks/ggfortify')`). You can now provide `label.show.legend`, e.g.
> 
> ```
> autoplot(prcomp(df), data = iris, colour = 'Species', label = TRUE, label.size = 3, label.show.legend = FALSE)
> ```
> 
> This should fix the "a" issue. Let me know if it fixes things for you. Thanks!

Hi,
I had a same problem with "fviz_pca_biplot()" and fixed with "label.show.legend = FALSE".
Thanks.
