### ISSUE TITLE
ggfortify fails with dev scales

### ISSUE THREAD

**Issue by hadley** [sinhrks/ggfortify#197]
With test failures like:

```R
ld$colour not equal to c("#F8766D", "#00BFC4", "#F8766D", "#F8766D").
4/4 mismatches
x[1]: "#FF0076"
y[1]: "#F8766D"

x[2]: "#00C3CA"
y[2]: "#00BFC4"

x[3]: "#FF0076"
y[3]: "#F8766D"

x[4]: "#FF0076"
y[4]: "#F8766D"
```

I suspect this is due to:

* `col_factor()` now tries to avoid interpolating qualitative RColorBrewer
  palettes. Instead, it attempts to assign a palette color to each factor level.
  Interpolation will still be used if there are more factor levels than
  available colors, and a warning will be emitted in that case (@jcheng5, #191).

**Comment by terrytangyuan** [comment]
@hadley Thanks for informing! I think we could relax the tests a bit here.

**Comment by hadley** [comment]
Having investigated this a bit more, I now think it's due to the switch to farver in `hue_pal()`. I'm going to try and get to the bottom of it today, but it's possible we'll roll back to the previous implementation in which case you probably won't need to do anything.

**Comment by terrytangyuan** [comment]
@hadley Thanks. Please keep me posted then.

**Comment by hadley** [comment]
Yup, looks like this is fixed on my end 😄

**Comment by terrytangyuan** [comment]
@hadley I am seeing some mismatches in color here https://cran.r-project.org/web/checks/check_results_ggfortify.html that needs to be corrected by 2020-03-20. For example:
```
     ── 6. Failure: autoplot ts works for multivariate timeseries (@test-ts.R#150) ─
     ld$fill not equal to rep(c("#00BFC4", "#F8766D"), 4).
     4/8 mismatches
     x[1]: "#F8766D"
     y[1]: "#00BFC4"
    
     x[3]: "#F8766D"
     y[3]: "#00BFC4"
    
     x[6]: "#00BFC4"
     y[6]: "#F8766D"
    
     x[8]: "#00BFC4"
     y[8]: "#F8766D"
```
Is that related to this issue?
