### ISSUE TITLE
Label Display Only Showing Row Number 

### ISSUE THREAD

**Issue by abresler** [sinhrks/ggfortify#20]
For some reason when I try to plot labels I can't ever  the actual labels even after renaming the rows

**Comment by sinhrks** [comment]
Thanks for the report. The issue is depending on {dplyr} version, and expected to be fixed in #21. Colud you try confirm?

**Comment by abresler** [comment]
Will give it a try again in a little.

Wonderful package, thanks for all the work you put into it

-- 
Alex Bresler

ASBC LLLC
asbcllc.com
917-455-0239

abresler@asbcllc.com
@abresler
