### ISSUE TITLE
autoplot.lm(which = 2) fails when residuals have class AsIs

### ISSUE THREAD

**Issue by richierocks** [sinhrks/ggfortify#202]
### System information
- **R version, OS**: R 4.0.0, macOS
- **ggfortify source**: CRAN
- **ggfortify version**: 0.4.10

### Describe the problem

If the response variable in a linear model created with `lm()` is wrapped in `I()`, then the residuals have type `AsIs`, which causes an error in `autoplot.lm()` when `which = 2`.

### Source code / logs / plots

``` r
library(ggplot2)
library(ggfortify)

# Create a linear regression model with response wrapped in I()
mdl_cars <- lm(I(dist ^ 2) ~ speed, data = cars)

# Automatic Q-Q plot
autoplot(mdl_cars, which = 2, ncol = 1)
#> Error in UseMethod("rescale"): no applicable method for 'rescale' applied to an object of class "AsIs"

# Remove the class of the residuals and try again
class(mdl_cars$residuals) <- NULL
autoplot(mdl_cars, which = 2, ncol = 1)
```

![](https://i.imgur.com/Ugr8y3S.png)

I think that the simplest fix is that `autoplot.lm()` should just drop the class of the residuals, so it is always dealing with a numeric vector.

**Comment by terrytangyuan** [comment]
Thanks for the detailed and reproducible issue! The suggested fix sounds good to me. Would you like to submit a pull request to fix that?
