### ISSUE TITLE
autoplot.lm() uses deprecated dplyr::arrange_()

### ISSUE THREAD

**Issue by dereksonderegger** [sinhrks/ggfortify#206]
It appears that autoplot.lm() uses deprecated dplyr functions. This is a problem because dplyr is now throwing warnings about this and people using ggfortify on a daily basis for creating diagnostic plots shouldn't think that ggfortify has been abandoned.

In particular lines 132, 136 and 140 in R/fortify_stats_lm.R use this to sort the fortified data by some column, but we can now just specify the arrangement without quoting  desc(abs(.resid)).  The same is true of the other instances.

I cloned ggfortify and made the changes and it appears to work. However when I went to build the package, it seems that there are a bunch more dplyr deprecated function calls in the vignettes "basics.Rmd", "plot_pca.Rmd", "plot_surv.Rmd", "plot_ts.Rmd". I was reluctant to dive into all of those vignettes just to report this bug.

I suspect that it wouldn't take to long to fix the vignettes, but I suspect this issue will touch a few other classes. I would be happy to start fixing those if it would be appreciated, but I didn't want to invest too much time before contacting people in charge.

library(ggfortify)
options(lifecycle_verbosity = 'error')  # error out on deprecation warnings
model <- lm( Volume ~ Height, data=trees)
autoplot(model)

The output (via reprex::reprex() ) is as follows:

library(ggfortify)
#> Loading required package: ggplot2
options(lifecycle_verbosity = 'error')
model <- lm( Volume ~ Height, data=trees)
autoplot(model)
#> Error: `arrange_()` was deprecated in lifecycle 0.7.0 and is now defunct.
#> Please use `arrange()` instead.
#> See vignette('programming') for more help

**Comment by terrytangyuan** [comment]
Thanks for filing this issue and clearly outlining what needs to be changed! 

Given that you already looked into this, we would really appreciate it if you could spend time diving into all remaining issues and send PRs to address those.

**Comment by dereksonderegger** [comment]
Git and I are having disagreements and I can't seem to create a pull request.  :( 
I made a repository on my GitHub that has all the changes and I think you'll be able to pull them from there.
https://github.com/dereksonderegger/ggfortify

**Comment by terrytangyuan** [comment]
@dereksonderegger Looks like @dprat just sent a PR to update the use of `select_()` in https://github.com/sinhrks/ggfortify/pull/207 so you probably want to make sure there's no overlap between your changes.

@dereksonderegger You can follow this instruction to create a pull request from your forked repo: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by terrytangyuan** [comment]
Oh it looks like your created a standalone repo instead of forking this original repo and thus you cannot create a pull request from there. Could you fork the repo instead and migrate the changes to the forked repo? Some instructions: https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo

**Comment by dereksonderegger** [comment]
#208 
My pull request for this issue is here.

**Comment by dprat** [comment]
In deed I saw this issue but I assumed that the use of `select_()` had not been changed since it was concerning `arrange()`function. sorry if you already made the modification !

**Comment by terrytangyuan** [comment]
@dprat No worries! Feel free to submit PRs if you see something missing.

@dereksonderegger Thanks! I'll take a look.

**Comment by terrytangyuan** [comment]
This has been fixed in #208. Thanks! If you see anything else that needs to be updated/improved, feel free to reach out again or submit PRs directly!
