### ISSUE TITLE
CITATION info wrong/incomplete

### ISSUE THREAD

**Issue by mllg** [sinhrks/ggfortify#209]
According to the R Journal (https://journal.r-project.org/archive/2016-2/index-bib.html), the citation should include the following information:

```bibtex
@Article{RJ-2016-060:2016,
  author       = {Yuan Tang and Masaaki Horikoshi and Wenxuan Li}, 
  title        = {ggfortify: Unified Interface to Visualize Statistical Results of Popular R Packages}, 
  journal      = {The R Journal},
  year         = 2016,
  volume       = 8,
  number       = 2,
  pages        = {474--485},
  month        = dec,
  url          = {https://doi.org/10.32614/RJ-2016-060}
}
```

Your citation info is lacking a DOI, only has a URL to the journal page (not the article itself) and incorrectly specifies `issue` instead of `number`.

**Comment by terrytangyuan** [comment]
Thanks for reporting this! I have submitted a PR to fix this in #210. Please help double check as well.
