### ISSUE TITLE
Possible issue adding labels to certain plots

### ISSUE THREAD

**Issue by alexandra-wall** [sinhrks/ggfortify#211]
Hello,

Thanks for your package.

While using the package I noticed the functions `autoplot.density`, `autoplot.aareg`,  do not seem to add axis labels to the plot when given the required arguments.
I tried to re-create the plots using just **ggplot2** functions and came across the same issue so it might be an issue with **ggplot2**, but I wasn't able to narrow it down further.

**ggfortify** version = 0.4.8
**ggplot2** version = 3.3.0

_Code to reproduce the issues_
`ggfortify:::autoplot.density(stats::density(airquality$Wind),
                                         xlab = "X axis Label",
                                         ylab = "Y axis Label")`

`ggfortify:::autoplot.aareg(survival::aareg(survival::Surv(Wind) ~ Temp + Month , 
                                                          data = airquality),
                                          xlab = "X axis Label",
                                          ylab = "Y axis Label")`

Thanks,
Alexandra

Plots produced by the code above are the following, in the same order as the code:
![image](https://user-images.githubusercontent.com/78794328/107371697-7bf5fc80-6adc-11eb-9a3a-adf172e2328e.png)
![image](https://user-images.githubusercontent.com/78794328/107371788-96c87100-6adc-11eb-8125-86ebe0dbe394.png)

**Comment by terrytangyuan** [comment]
Thanks for reporting! This should be fixed now. Could you try the new version from GitHub?

**Comment by terrytangyuan** [comment]
Fixed in https://github.com/sinhrks/ggfortify/commit/d3b5c359586b82d94245002f6841bde37ab3c0dd and https://github.com/sinhrks/ggfortify/commit/912ba6d39feb1537b30997632b1d125500c1058d.

**Comment by alexandra-wall** [comment]
Tested with the new version from GitHub and they are showing up now! 

Thank you for such a quick response.

![image](https://user-images.githubusercontent.com/78794328/107375428-a5b12280-6ae0-11eb-9af2-1fc54f5d8942.png)

**Comment by terrytangyuan** [comment]
Great! Let me know if you find anything else erroneous.
