### ISSUE TITLE
ggrepel not working with new version of R and RStudio

### ISSUE THREAD

**Issue by ncep112** [sinhrks/ggfortify#219]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Version 10.15.7
- **ggfortify installed from (e.g. CRAN or Github)**: CRAN
- **ggfortify version**: 0.4.14
- **Exact command to reproduce**: autoplot(prcomp(USArrests), label.repel = TRUE, loadings = TRUE, loadings.label.repel = TRUE)

### Describe the problem
There seems to be a new bug with ggfortify loadings.label.repel. This code no longer works with updated R (version 4.1.2) and RStudio (version 2022.02.0+443), when it previously worked with older versions. 

### Source code / logs / plots
autoplot(prcomp(USArrests), label.repel = TRUE, loadings = TRUE, loadings.label.repel = TRUE)
![Rplot](https://user-images.githubusercontent.com/100046736/154818033-242cd4ce-da0b-4352-ab94-c51423eb3ae6.png)

**Comment by terrytangyuan** [comment]
Was the problem solved?

**Comment by ncep112** [comment]
A colleague was able to replicate the scripts above without getting the same error, so I assume it's an issue with my computer rather than with ggfortify loadings.label.repel or the new version of R. Thank you for your help in developing and maintaining this tool!
