### ISSUE TITLE
PCA score results are different

### ISSUE THREAD

**Issue by YonghuiDong** [sinhrks/ggfortify#221]
With autoplot
```
library(ggfortify)
df <- iris[1:4]
pca_res <- prcomp(df, scale. = TRUE)
autoplot(pca_res, data = iris, colour = 'Species')
```

![b88e6f30-85c9-47aa-a9c6-025b88bd8442](https://user-images.githubusercontent.com/22663189/160235759-1fff35af-c9bf-4eba-a926-7e01869242d5.png)

Self calculated 

```
percentage <-round(pca_res$sdev / sum(pca_res$sdev) * 100, 2)
percentage
53.53 29.96 12.00  4.51
```

You can see that the variance explained by `PC1` and `PC2` are: **53.53** and **29.96**, respectively, which are very different from the result shown in the above figure.

score plot using ggplot2

```
ggplot(pca_res, aes( x = PC1, y = PC2, color = Group)) +
    geom_point() +
    theme_bw() +
    xlab(percentage[1]) +
    ylab(percentage[2])
```
![555f0809-065f-4219-b56f-e75cb3d1e1dd](https://user-images.githubusercontent.com/22663189/160236122-a8c9ccb3-0eed-44b0-a589-bc0f9b24b583.png)

**Comment by terrytangyuan** [comment]
Is this no longer an issue?

**Comment by terrytangyuan** [comment]
Great
