### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by lalas** [sinhrks/ggfortify#33]
Hello,

First and foremost, I would like to thank you and congratulate you on the effort you have put into this project. I was playing with the gglagplot function, when i noticed that it doesn't take a parameters to label the axis (y-axis - now get a "Data" label).

I was wondering if you can edit the list parameters, to accept ... (ellipsis), so that the parameters can be passed to ggplot function.

Thanks

**Comment by sinhrks** [comment]
Hi, thank you for your feedback:) Currently, you can:

```
gglagplot(AirPassengers) + ylab('Whatever')
```

![rplot](https://cloud.githubusercontent.com/assets/1696302/6649650/3f3645ca-ca33-11e4-973b-09627b964cbd.png)

> I was wondering if you can edit the list parameters, to accept ... (ellipsis), so that the parameters can be passed to ggplot function.

Do you expect keywords supported in `qplot` function works, ``main``, ``asp``, ``xlab``, ``ylab``, ``xlim`` and ``ylim``? 

```
# ggplot2 behaviour

# This doesn't work (y label will be Petal.Length
ggplot(data = iris, ylab = 'Y LABEL') + geom_point(aes(x = Petal.Width, y = Petal.Length))

# Otherwise qplot works (y label will be 'Y LABEL')
qplot(data = iris, x = Petal.Width, y = Petal.Length, geom = 'point', ylab = 'Y LABEL')
```

**Comment by sinhrks** [comment]
I expect this meets your expectations. Pls check:

- http://rpubs.com/sinhrks/basics

> Because autoplot returns ggplot instance, you can decorate it either way.
>   - Use + operator after calling autoplot.
>   - Use common options supported in ggplot2::qplot. xlim, ylim, log, main, xlab, ylab and asp.

**Comment by lalas** [comment]
Thank you very much.. Your replies made me appreciate the design principles of ggfortify. 

Cheers

**Comment by sinhrks** [comment]
Thanks to confirm. If you want any other options, please lmk :)

**Comment by lalas** [comment]
Thank you very much! :)

On Tue, Mar 17, 2015 at 11:56 AM, Sinhrks <notifications@github.com> wrote:

> Thanks to confirm. If you want any other options, please lmk :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinhrks/ggfortify/issues/33#issuecomment-82433328>.
>



-- 
"Life may not be the party we hoped for, but as long as we are here we
might as well dance."

"A new truth does not triumph by convincing its opponents and making them
see the light, but rather because its opponents eventually die out, and a
new generation grows up that is familiar with it"

"If we take eternity to mean not infinite temporal duration but
timelessness, then eternal life belongs to those who live in the present." ―
Ludwig Wittgenstein

"Perfection is achieved, not when there is nothing more to add, but when
there is nothing left to take away" ― Antoine de Saint-Exupéry
