### ISSUE TITLE
DOC: Migrate rpubs to vignette

### ISSUE THREAD

**Issue by sinhrks** [sinhrks/ggfortify#59]
- [x] Prepare more vignette merging existing RPubs docs
- [x] Release next version (Dec, 2015 or Jan, 2016 following CRAN policy?)
- [ ] Add link to vignette from existing RPubs.
- [x] Rename ``VignetteIndexEntry``

**Comment by sinhrks** [comment]
@terrytangyuan Vignettes of current CRAN version (0.0.4) has limited info corresponds to "basics.Rmd". I've moved other RPubs to "vignettes" directly already, and planning to include them in next release. How about following 6 files?

- basics
- plot_dist
- plot_lm
- plot_pca
- plot_surv
- plot_ts

**Comment by terrytangyuan** [comment]
Sounds good. I'll work on them whenever I have time. Where should the translated version be placed?

**Comment by sinhrks** [comment]
I don't have experience of localization using knitr, splitting R programs to external file makes your work easier?

- http://yihui.name/knitr/demo/externalization/

**Comment by terrytangyuan** [comment]
This can be closed, right?

**Comment by sinhrks** [comment]
yeah wil update on rpubs.
