### ISSUE TITLE
ggfortify installation fails: could not find function "eval"

### ISSUE THREAD

**Issue by sinhrks** [sinhrks/ggfortify#67]
In both ``install.packages`` and ``install_github``.

```
Error in eval(expr, envir, enclos) : could not find function "eval"
Error : unable to load R code in package ‘ggfortify’
ERROR: lazy loading failed for package ‘ggfortify’
```

Maybe related to ``ggplto2`` dev version: 

- https://github.com/jrnold/ggthemes/issues/36
- https://github.com/dkahle/ggmap/issues/65

**Comment by lionel-** [comment]
This error comes with these (possibly unrelated) warnings:
```r
Warning: replacing previous import by ‘grid::arrow’ when loading ‘ggfortify’
Warning: replacing previous import by ‘grid::unit’ when loading ‘ggfortify’
Warning: replacing previous import by ‘scales::alpha’ when loading ‘ggfortify’
```
this probably could be fixed by importing only the functions you need instead of importing the whole packages.

**Comment by sinhrks** [comment]
Thanks, this is one thing but not only that. We need to fix internal impl to meet with ggplot2 change as below.

- https://github.com/jrnold/ggthemes/pull/37/files
