### ISSUE TITLE
TST: Creating vignettes fails on Travis CI repeatedly

### ISSUE THREAD

**Issue by sinhrks** [sinhrks/ggfortify#72]
From yesterday, following error occurs on Travis CI repeatedly. Maybe any dependencies has been changed? Strangely I can't reproduce the issue on my local.

The branch is unmodified fork of current master:

- https://travis-ci.org/sinhrks/ggfortify/jobs/88574863

```
* creating vignettes ... ERROR
Loading required package: proto
Loading required package: ggplot2
Warning in rgl.init(initValue, onlyNULL) :
  RGL: unable to open X11 display
Warning in fun(libname, pkgname) : Error in 'rgl_init'
Don't know how to automatically pick scale for object of type complex. Defaulting to continuous
Don't know how to automatically pick scale for object of type complex. Defaulting to continuous
Quitting from lines 112-121 (plot_pca.Rmd) 
Error: processing vignette 'plot_pca.Rmd' failed with diagnostics:
Discrete value supplied to continuous scale
Execution halted
```

The error message says it is related to ``lfda`` block.

```
library(lfda)

# Local Fisher Discriminant Analysis (LFDA)
model <- lfda(iris[-5], iris[, 5], 4, metric="plain")
autoplot(model, data = iris, frame = TRUE, frame.colour = 'Species')

# Kernel Local Fisher Discriminant Analysis (KLFDA)
model <- klfda(kmatrixGauss(iris[-5]), iris[, 5], 4, metric="plain")
autoplot(model, data = iris, frame = TRUE, frame.colour = 'Species')
```

**Comment by sinhrks** [comment]
@terrytangyuan Any thoughts? Either results can be complex number logically...?

**Comment by terrytangyuan** [comment]
This is very strange. I believe something might have changes rgl package, which tries to open the x11 device. Nothing has been changed for lfda package. I haven't looked into the PR yet but it seems like that the failure only happens when you merge PR even when it's passed during the PR.

**Comment by terrytangyuan** [comment]
Maybe you can skip Travis for lfda plotting unit tests for now.

**Comment by terrytangyuan** [comment]
If the tests and vignettes run fine locally, let's just skip the vignettes building during Travis for now. Try something like:
r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

**Comment by sinhrks** [comment]
Thanks, I temporary removed it by changing extension (as other vignettes works).
