### ISSUE TITLE
COMPAT: Test failure in CRAN

### ISSUE THREAD

**Issue by sinhrks** [sinhrks/ggfortify#78]
Received kind email from CRAN:

> Presumably from an update of one of
> 
> 1  changepoint 2015-11-09
> 2   timeSeries 2015-11-09
> 
> we now see your package fail its tests with
> 
>  checking tests ... ERROR
> Running the tests in ‘tests/test-all.R’ failed.
> Last 13 lines of output:
>   3: In princomp.default(df, center = TRUE, scale = FALSE) :
>    extra arguments 'center', 'scale' will be disregarded
>   4: In princomp.default(df, center = FALSE, scale = FALSE) :
>    extra arguments 'center', 'scale' will be disregarded
>   5: In princomp.default(USArrests, center = TRUE, scale = TRUE) :
>    extra arguments 'center', 'scale' will be disregarded
>   6: In princomp.default(USArrests, center = FALSE, scale = TRUE) :
>    extra arguments 'center', 'scale' will be disregarded
>   7: In princomp.default(USArrests, center = TRUE, scale = FALSE) :
>    extra arguments 'center', 'scale' will be disregarded
>   8: In princomp.default(USArrests, center = FALSE, scale = FALSE) :
>    extra arguments 'center', 'scale' will be disregarded
>   Execution halted

**Comment by terrytangyuan** [comment]
Submitting new version?

**Comment by sinhrks** [comment]
Yes, needs new version. I'm going to check #59 and #72 at this chance. Do you have anything should be included?

**Comment by terrytangyuan** [comment]
Not really. I am only working on a draft article but it doesn't need to be included.
